[project]
name = 'entropy-reversal-energy-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.post-scarcity-economics-manager]
path = 'contracts/post-scarcity-economics-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.thermodynamic-reversal-coordinator]
path = 'contracts/thermodynamic-reversal-coordinator.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
